[server]
enableStaticServing = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#8C1D40"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E5E7EB"
textColor = "#1A1A1A"
linkColor = "#0366D6"
borderColor = "#E5E7EB"
baseRadius = "0.425rem"
font = "'IBM Plex Sans':https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&display=swap"
codeFont = "'IBM Plex Mono':https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap"
codeBackgroundColor = "#E5E7EB"
showSidebarBorder = true
headingFontSizes = ["40px", "32px", "24px"]
headingFontWeights = 500

[theme.sidebar] 
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E5E7EB"