"""Turn-level SFT generators for CaSiNo.

Each generator walks through real dialogues turn-by-turn and produces
rows whose completion uses XML-delimited thought/talk fields with a JSON
action block::

    <thought>...</thought>
    <talk>...</talk>
    <action>{"type": "...", ...}</action>

The ``thought`` field is always generated by an external LLM (see
``llm_thoughts.py``).  ``talk`` comes directly from the source data,
and ``action`` is parsed/inferred from the utterance text and dataset
annotations.
"""

from __future__ import annotations

import logging
import re

from rl.handlers.casino.dataset import (
    _META_TURNS,
    PRIORITY_TO_POINTS,
    STRATEGY_LABEL_MAP,
    STRATEGY_LABELS,
    sanitize_unicode,
)

logger = logging.getLogger(__name__)

CA_ITEMS = ["food", "water", "firewood"]
CA_COUNTS: dict[str, int] = {"food": 3, "water": 3, "firewood": 3}

_NUM_WORDS: dict[str, int] = {
    "zero": 0,
    "no": 0,
    "one": 1,
    "a": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "all": -1,
}

_FORMAT_SPEC = (
    "Produce your next negotiation turn using the following XML format:\n"
    "<thought>your internal reasoning (point arithmetic, partner priority "
    "estimate, justification)</thought>\n"
    "<talk>your natural language response to your partner</talk>\n"
    '<action>{"type": "offer"|"counter"|"accept"|"reject", '
    "...item allocations for yourself}</action>"
)


def _build_sft_prompt(
    vals: dict[str, int],
    max_pts: int,
    history: str | None = None,
) -> str:
    """Build an SFT prompt that exactly mirrors NegotiationEnv.build_learner_prompt."""
    lines = [
        "You are negotiating with your campsite neighbor over extra supply "
        "of food, water, and firewood for your camping trip.",
        "You MUST respond with exactly one <thought>, one <talk>, and one <action> XML block.",
        "",
        "Items available: 3 Food, 3 Water, 3 Firewood",
        (
            f"Your point values: "
            f"Food={vals['food']}pts, "
            f"Water={vals['water']}pts, "
            f"Firewood={vals['firewood']}pts"
        ),
        f"Max possible points: {max_pts}pts",
        "",
    ]
    if history:
        lines.append("Dialogue so far:")
        lines.append(history)
        lines.append("")
    lines.append(_FORMAT_SPEC)
    return "\n".join(lines)


def _parse_quantities(
    text: str,
    items: list[str],
    counts: dict[str, int],
) -> dict[str, int] | None:
    """Extract item quantities mentioned in negotiation text."""
    lower = text.lower()
    found: dict[str, int] = {}
    for item in items:
        patterns = [
            rf"(\d+)\s+(?:packages?\s+of\s+)?{item}s?",
            rf"(zero|no|one|a|two|three|four|five|all)\s+(?:of\s+the\s+|packages?\s+of\s+)?{item}s?",
        ]
        for pat in patterns:
            m = re.search(pat, lower)
            if m:
                v = m.group(1)
                if v.isdigit():
                    found[item] = int(v)
                elif v in _NUM_WORDS:
                    n = _NUM_WORDS[v]
                    found[item] = counts.get(item, 3) if n == -1 else n
                break
    for item in list(found):
        found[item] = min(found[item], counts.get(item, 3))
    return found or None


_NEGATORS = {"not", "don't", "can't", "cannot", "n't", "no", "never"}


def _has_negation_before(text: str, match_start: int) -> bool:
    window = text[max(0, match_start - 20) : match_start].lower().split()
    return bool(set(window) & _NEGATORS)


def _action_type(text: str, has_prior_offer: bool) -> str:
    lower = text.lower()
    reject_kw = (
        "no deal",
        "reject",
        "can't agree",
        "cannot agree",
        "walk away",
        "no way",
        "not going to work",
        "don't agree",
        "do not agree",
        "can't accept",
        "cannot accept",
        "don't accept",
        "do not accept",
    )
    accept_kw = (
        "deal",
        "accept",
        "agree",
        "sounds good",
        "works for me",
        "that's fine",
        "okay deal",
        "ok deal",
        "you got it",
        "that works",
        "i can do that",
    )
    if any(k in lower for k in reject_kw):
        return "reject"
    for kw in accept_kw:
        idx = lower.find(kw)
        if idx != -1 and not _has_negation_before(lower, idx):
            return "accept"
    return "counter" if has_prior_offer else "offer"


def _fmt_history_ca(chat_logs: list[dict], agent: str, up_to: int) -> str:
    lines: list[str] = []
    for t in chat_logs[:up_to]:
        if t["text"] in _META_TURNS:
            continue
        who = "You" if t["id"] == agent else "Partner"
        lines.append(f"{who}: {sanitize_unicode(t['text'])}")
    return "\n".join(lines) or "(no dialogue yet)"


def _extract_outcome_ca(
    chat_logs: list[dict],
    agent: str,
    agent_vals: dict[str, int],
    partner_vals: dict[str, int],
) -> dict:
    """Extract the final deal outcome from CaSiNo chat logs."""
    partner = "mturk_agent_2" if agent == "mturk_agent_1" else "mturk_agent_1"
    for src, is_agent in ((agent, True), (partner, False)):
        for turn in chat_logs:
            if turn["text"] != "Submit-Deal" or turn["id"] != src:
                continue
            youget = turn.get("task_data", {}).get("issue2youget", {})
            if not all(v != "" for v in youget.values()):
                continue
            src_alloc = {k.lower(): int(v) for k, v in youget.items()}
            if is_agent:
                agent_alloc = src_alloc
                partner_alloc = {k: CA_COUNTS[k] - v for k, v in agent_alloc.items()}
            else:
                partner_alloc = src_alloc
                agent_alloc = {k: CA_COUNTS[k] - v for k, v in partner_alloc.items()}
            return {
                "deal_reached": True,
                "agent_allocation": agent_alloc,
                "partner_allocation": partner_alloc,
                "agent_points": sum(agent_alloc[k] * agent_vals[k] for k in CA_ITEMS),
                "partner_points": sum(partner_alloc[k] * partner_vals[k] for k in CA_ITEMS),
            }
    return {
        "deal_reached": False,
        "agent_allocation": {},
        "partner_allocation": {},
        "agent_points": 0,
        "partner_points": 0,
    }


def generate_turns_ca(instances: list[dict]) -> list[dict]:
    rows: list[dict] = []

    for inst in instances:
        chat_logs = inst["chat_logs"]
        annotations = inst["annotations"]
        pinfo = inst["participant_info"]

        for agent in ("mturk_agent_1", "mturk_agent_2"):
            partner = "mturk_agent_2" if agent == "mturk_agent_1" else "mturk_agent_1"
            v2i = pinfo[agent]["value2issue"]
            vals = {item.lower(): PRIORITY_TO_POINTS[lv] for lv, item in v2i.items()}
            max_pts = sum(CA_COUNTS[i] * vals[i] for i in CA_ITEMS)

            partner_v2i = pinfo[partner]["value2issue"]
            partner_vals = {
                item.lower(): PRIORITY_TO_POINTS[lv] for lv, item in partner_v2i.items()
            }
            full_dialogue = _fmt_history_ca(chat_logs, agent, len(chat_logs))
            dialogue_outcome = _extract_outcome_ca(chat_logs, agent, vals, partner_vals)

            has_prior = False
            dialogue_turn_idx = 0

            for idx, turn in enumerate(chat_logs):
                # ── Final deal (Submit-Deal) ──
                if turn["text"] == "Submit-Deal" and turn["id"] == agent:
                    youget = turn.get("task_data", {}).get("issue2youget", {})
                    if all(v != "" for v in youget.values()):
                        alloc = {k.lower(): int(v) for k, v in youget.items()}
                        hist = _fmt_history_ca(chat_logs, agent, idx)
                        rows.append(
                            {
                                "task": "turn_ca",
                                "prompt": _build_sft_prompt(vals, max_pts, history=hist),
                                "talk": "I'd like to submit this deal.",
                                "action": {"type": "offer", **alloc},
                                "strategy_label": None,
                                "agent_values": vals,
                                "partner_values": partner_vals,
                                "full_dialogue": full_dialogue,
                                "dialogue_outcome": dialogue_outcome,
                                "turn_index": dialogue_turn_idx,
                            }
                        )
                    continue

                if turn["text"] in _META_TURNS:
                    continue
                if turn["id"] != agent:
                    dialogue_turn_idx += 1
                    continue

                prior_real = [
                    t for t in chat_logs[:idx] if t["text"] not in _META_TURNS
                ]

                text = sanitize_unicode(turn["text"])
                parsed = _parse_quantities(text, CA_ITEMS, CA_COUNTS)
                atype = _action_type(text, has_prior)

                if not prior_real:
                    if parsed is not None:
                        alloc = {i: parsed.get(i, 0) for i in CA_ITEMS}
                    else:
                        best_item = max(CA_ITEMS, key=lambda i: vals[i])
                        alloc = {
                            i: (CA_COUNTS[i] if i == best_item else 1) for i in CA_ITEMS
                        }
                    atype = "offer"
                    has_prior = True
                    action = {"type": atype, **alloc}
                    rows.append(
                        {
                            "task": "turn_ca",
                            "prompt": _build_sft_prompt(vals, max_pts),
                            "talk": text,
                            "action": action,
                            "strategy_label": None,
                            "agent_values": vals,
                            "partner_values": partner_vals,
                            "full_dialogue": full_dialogue,
                            "dialogue_outcome": dialogue_outcome,
                            "turn_index": dialogue_turn_idx,
                        }
                    )
                    dialogue_turn_idx += 1
                    continue

                strat: str | None = None
                if idx < len(annotations):
                    ann = annotations[idx]
                    raw_label = ann[1] if len(ann) > 1 else ""
                    if raw_label and "non-strategic" not in raw_label:
                        labels = [
                            STRATEGY_LABEL_MAP.get(s.strip(), s.strip())
                            for s in raw_label.split(",")
                        ]
                        labels = [lb for lb in labels if lb in STRATEGY_LABELS]
                        if labels:
                            strat = ", ".join(labels)

                if parsed is not None:
                    alloc = {i: parsed.get(i, 0) for i in CA_ITEMS}
                    has_prior = True
                elif atype in ("accept", "reject"):
                    alloc = {}
                else:
                    continue

                action = {"type": atype, **alloc} if alloc else {"type": atype}
                hist = _fmt_history_ca(chat_logs, agent, idx)

                rows.append(
                    {
                        "task": "turn_ca",
                        "prompt": _build_sft_prompt(vals, max_pts, history=hist),
                        "talk": text,
                        "action": action,
                        "strategy_label": strat,
                        "agent_values": vals,
                        "partner_values": partner_vals,
                        "full_dialogue": full_dialogue,
                        "dialogue_outcome": dialogue_outcome,
                        "turn_index": dialogue_turn_idx,
                    }
                )
                dialogue_turn_idx += 1

    return rows


TURN_GENERATORS: dict[str, type] = {
    "turn_ca": generate_turns_ca,
}
